### ISSUE TITLE
SOM Inquiry 

### ISSUE THREAD

**Issue by Donnyp751** [TechNexion-Vision/nxp_evk_camera#1]
I noticed that the driver is only supporting i.MX8 currently, I was wondering if there is any electrical constraints that would block an i.MX6 platform from being used with these cameras, and if so how difficult would it be to port this library to the i.MX6 to use cameras like the AR0234?

Thanks,
Donald

**Comment by a8111892** [comment]
You can refer to  [i.MX8mm-tevs](https://github.com/TechNexion/linux-tn-imx/blob/tn-imx_6.1.55_2.2.0-stable/arch/arm64/boot/dts/freescale/overlays/imx8mm-edm-g-wb-tevs-overlay.dts), it also using as same as iMX6 CSI driver without ISI. We work well with i.MX8mm.
